### PR TITLE
Use `prepare`

### PR DESCRIPTION
**Pull request by sugarshin**
Can you check this please.

### CODE REVIEW

**Comment by brunocodutra** [comment]
Thanks for the patch! 

I actually wasn't aware that could be done and it's a great idea, but I think we should be hooking up `prepare` instead of `prepublishOnly`? 

See npm/npm#3055

**Comment by sugarshin** [comment]
Thanks for reply.

I didn’t know `prepare` . I think `prepare` is more better. I’ll update PR later.
Thank you!

**Comment by sugarshin** [comment]
@brunocodutra Please re-check.

**Comment by brunocodutra** [comment]
Works like a charm, thanks again!

**Pull request merged**
