### PR TITLE
Handle the case of a template with no <head></head>

### PR DESCRIPTION
**Pull request by khalwat**
As per the discussion here:

https://github.com/brunocodutra/webapp-webpack-plugin/issues/134

Signed-off-by: Andrew Welch <andrew@nystudio107.com>

### CODE REVIEW

**Comment by khalwat** [comment]
This should do the trick @brunocodutra -- thanks for your help with the tests/fixtures!

**Comment by brunocodutra** [comment]
Looks great, thanks!

**Comment by khalwat** [comment]
Awesome! Will you be tagging a new release, or should I just pull from `master` ?

**Comment by brunocodutra** [comment]
I don't have the bandwidth to cut a release just now, because I need to finish that other PR, can you do with pulling from master for now?

**Comment by khalwat** [comment]
Yep, no worries, will do, and thank you!

**Pull request merged**
